In [3]:
import pandas as pd

In [4]:
# series 1d 1 col , dataframe 2d rxc

In [5]:
#series
pd.Series([1,2,3,4],name="num")

0    1
1    2
2    3
3    4
Name: num, dtype: int64

In [6]:
di={
    "name":["aman","rahul","gopi","mohd","keshav","monika"],
    "age":[12,13,11,11,14,15]
}

df=pd.DataFrame(di)
df.head()

     name  age
0    aman   12
1   rahul   13
2    gopi   11
3    mohd   11
4  keshav   14

In [7]:
#add col
marks=[12,1,3,14,15,0]
df.insert(1,"marks",marks)
df.head()

     name  marks  age
0    aman     12   12
1   rahul      1   13
2    gopi      3   11
3    mohd     14   11
4  keshav     15   14

In [8]:
df=pd.read_csv("data/tipsdataset.csv")

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   gender      244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [9]:
df.shape

(244, 7)

In [10]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [11]:
df["gender"].value_counts()

gender
Male      157
Female     87
Name: count, dtype: int64

In [13]:
df.isnull().sum()

total_bill    0
tip           0
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64

In [13]:
import pandas as pd

df = pd.read_csv("DATA/tipsdataset.csv")
df.head()

   total_bill   tip  gender smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
url="https://raw.githubusercontent.com/arun-avasthi/PBELSEVEN/refs/heads/main/DATA/tipsdataset.csv"

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/arun-avasthi/PBELSEVEN/refs/heads/main/DATA/tipsdataset.csv")
df.head()

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)>

In [22]:
male = df["gender"] == "Male"
smoker = df["smoker"] == "Yes"

df[male & smoker].describe()

       total_bill        tip      size
count   60.000000  60.000000  60.00000
mean    22.284500   3.051167   2.50000
std      9.911845   1.500120   0.89253
min      7.250000   1.000000   1.00000
25%     15.272500   2.000000   2.00000
50%     20.390000   3.000000   2.00000
75%     28.572500   3.820000   3.00000
max     50.810000  10.000000   5.00000

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64