In [2]:
import pandas as pd

In [ ]:
# series 1d 1 col , dataframe 2d rxc

In [3]:
#series
pd.Series([1,2,3,4],name="num")

0    1
1    2
2    3
3    4
Name: num, dtype: int64

In [4]:
di={
    "name":["aman","rahul","gopi","mohd","keshav","monika"],
    "age":[12,13,11,11,14,15]
}

df=pd.DataFrame(di)
df.head()

     name  age
0    aman   12
1   rahul   13
2    gopi   11
3    mohd   11
4  keshav   14

In [5]:
#add col
marks=[12,1,3,14,15,0]
df.insert(1,"marks",marks)
df.head()

     name  marks  age
0    aman     12   12
1   rahul      1   13
2    gopi      3   11
3    mohd     14   11
4  keshav     15   14

In [7]:
df=pd.read_csv("data/tipsdataset.csv")

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   gender      244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [9]:
df.shape

(244, 7)

In [10]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [11]:
df["gender"].value_counts()

gender
Male      157
Female     87
Name: count, dtype: int64

In [13]:
df.isnull().sum()

total_bill    0
tip           0
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64